# Generated by Django 5.0.6 on 2025-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='class',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='created_at',
        ),
    ]
