# Generated by Django 5.0.6 on 2025-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_enrolled_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
