# Generated by Django 5.0.6 on 2025-05-24 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_progress', to='docs.document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_progress',
                'unique_together': {('student', 'document')},
            },
        ),
    ]
